-- SPRINT 1: CREACIÓN DE ESQUEMA PRINCIPAL

-- 1. Tabla de Usuarios
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR NOT NULL,
    email VARCHAR UNIQUE NOT NULL,
    password_hash VARCHAR NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- 2. Tabla de Proyectos
CREATE TABLE projects (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR NOT NULL,
    description TEXT NOT NULL,
    image_url VARCHAR,
    funding_goal DECIMAL NOT NULL,
    current_amount DECIMAL DEFAULT 0,
    deadline TIMESTAMP NOT NULL,
    status VARCHAR DEFAULT 'DRAFT' NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- 3. Tabla de Contribuciones
CREATE TABLE contributions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    amount DECIMAL NOT NULL,
    status VARCHAR NOT NULL, -- PENDING, COMPLETED, REFUNDED
    created_at TIMESTAMP DEFAULT NOW()
);

-- 4. Tabla de Transacciones
CREATE TABLE transactions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    contribution_id UUID NOT NULL REFERENCES contributions(id) ON DELETE CASCADE,
    reference_code VARCHAR,
    payment_method VARCHAR,
    amount DECIMAL NOT NULL,
    status VARCHAR NOT NULL, -- SUCCESS, DECLINED, ERROR
    processed_at TIMESTAMP DEFAULT NOW()
);